[tool.poetry]
name = "regibox"
version = "0.1.0"
description = "Automatically enroll in Regibox Crossfit classes"
authors = ["Martim Lobao <m@rtimlobao.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
beautifulsoup4 = "^4.12.2"
python-dotenv = "^1.0.0"
pytz = "^2023.3"
requests = "^2.31.0"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
coverage = "^7.2.7"
ipython = "^8.14.0"
isort = "^5.12.0"
mypy = "^1.4.0"
pylint = "^2.17.4"
pytest = "^7.4.0"
ruff = "^0"
types-beautifulsoup4 = "^4.12.0.5"
types-pytz = "^2023.3.0.0"
types-requests = "^2.31.0.1"
yamllint = "^1.32.0"

[tool.black]
line_length = 99

[tool.isort]
profile = "black"
color_output = true
known_first_party = ["regibox"]
line_length = 99

[tool.mypy]
python_version = "3.10"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
