target-version = "py310"
line-length = 99
extend-select = [
    "A",
    "AIR",
    "ANN",
    "ARG",
    "ASYNC",
    "B",
    "BLE",
    "C4",
    "C90",
    # "COM",
    "CPY",
    # "D",
    "DJ",
    "DTZ",
    "E",
    # "EM",
    "ERA",
    "EXE",
    "F",
    "FA",
    "FBT",
    "FIX",
    "FLY",
    "G",
    "I",
    "ICN",
    "INP",
    "INT",
    "ISC",
    "N",
    "NPY",
    "PD",
    "PERF",
    "PGH",
    "PIE",
    "PL",
    "PLC",
    "PLE",
    "PLR",
    "PLW",
    "PT",
    "PTH",
    "PYI",
    "Q",
    "RET",
    "RSE",
    "RUF",
    "S",
    "SIM",
    "SLF",
    "SLOT",
    "T10",
    "T20",
    "TCH",
    "TD",
    "TID",
    # "TRY",
    "UP",
    "W",
    "YTT",
]

[per-file-ignores]
"*_test.py" = ["S101"]
"test_*.py" = ["S101"]

[pydocstyle]
convention = "google"

[pycodestyle]
max-doc-length = 80
