target-version = "py311"
line-length = 99
select = ["ALL"]
ignore = [
    "COM",  # out-blacks black
    "D",
    "EM",
    "TRY",
]
fixable = ["ALL"]

[per-file-ignores]
"*_test.py" = ["S101"]
"test_*.py" = ["S101"]

[pydocstyle]
convention = "google"

[pycodestyle]
max-doc-length = 80
