---
name: Trigger Regibox Holidays
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    # Dia de Ano Novo
    # Sexta-Feira Santa
    # Páscoa
    - cron: 50 8 23 4 *  # 25 de Abril
    - cron: 50 8 29 4 *  # Dia do Trabalhador
    # Corpo de Deus
    # Assunção de Nossa Senhora
    - cron: 50 8 8 6 *  # Dia de Portugal
    - cron: 50 8 3 10 *  # Implantação da República
    - cron: 50 8 30 10 *  # Dia de Todos os Santos
    - cron: 50 8 29 11 *  # Restauração da Independência
    - cron: 50 8 6 12 *  # Dia da Imaculada Conceição
    # Natal

jobs:
  weekday:
    name: Check weekday
    runs-on: ubuntu-latest
    outputs:
      weekday: ${{ steps.set.outputs.WEEKDAY }}
    steps:
      - id: set
        run: |
          echo "hello"
          WEEKDAY=$([[ "$(date -d '+2 days' +%u)" -lt 6 ]] && echo "true" || echo "false")
          echo "$WEEKDAY"
        # echo "$WEEKDAY" >> "$GITHUB_OUTPUT"
  build:
    name: Trigger Regibox run
    runs-on: ubuntu-latest
    needs:
      - weekday
    # only for holidays that are not on weekends
    if: needs.weekday.outputs.WEEKDAY == 'true'
    steps:
      - name: Get class date
        run: |
          echo "CLASS_DATE=$(date -d '+2 days' +%F)" >> $GITHUB_ENV
          echo "CLASS_TIME='09:00'" >> $GITHUB_ENV
          echo "CLASS_TYPE='WEEKEND WOD RATO'" >> $GITHUB_ENV
          echo "${{ needs.weekday.outputs.WEEKDAY }}"
