---
name: Trigger Regibox Holidays
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    # Dia de Ano Novo
    # Sexta-Feira Santa
    # Páscoa
    # DST starts
    - cron: 50 8 23 4 *  # 25 de Abril
    - cron: 50 8 29 4 *  # Dia do Trabalhador
    # Corpo de Deus
    # Assunção de Nossa Senhora
    - cron: 50 8 8 6 *  # Dia de Portugal
    - cron: 50 8 3 10 *  # Implantação da República
    # DST ends
    - cron: 50 9 30 10 *  # Dia de Todos os Santos
    - cron: 50 9 29 11 *  # Restauração da Independência
    - cron: 50 9 6 12 *  # Dia da Imaculada Conceição
    # Natal

jobs:
  weekday:
    name: Check weekday
    runs-on: ubuntu-latest
    outputs:
      weekday: ${{ steps.set.outputs.WEEKDAY }}
    steps:
      - id: set
        run: |
          echo "WEEKDAY=$([[ "$(date -d '+2 days' +%u)" -lt 6 ]] && echo "true" || echo "false")" >> "$GITHUB_OUTPUT"
  build:
    name: Trigger Regibox run
    runs-on: ubuntu-latest
    needs:
      - weekday
    # only for holidays that are not on weekends
    if: needs.weekday.outputs.WEEKDAY == 'true'
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Load cached Poetry installation
        id: cached-poetry
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry
      - name: Install Poetry
        if: steps.cached-poetry.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/
          key: |
            venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install Dependencies using Poetry
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --with dev
      - name: Get class date
        run: |
          echo "CLASS_DATE=$(date -d '+2 days' +%F)" >> $GITHUB_ENV
          echo "CLASS_TIME='10:00'" >> $GITHUB_ENV
          echo "CLASS_TYPE='WEEKEND WOD RATO'" >> $GITHUB_ENV
      - name: Regibox enroll
        run: poetry run python -m regibox ${{ env.CLASS_DATE }} ${{ env.CLASS_TIME }} ${{ env.CLASS_TYPE }}
        env:
          COOKIE: ${{ secrets.COOKIE }}
      - name: Send mail
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: >
            Regibox HOLIDAY Auto-enroll: ${{ job.status }} for ${{ env.CLASS_TYPE }} on ${{ env.CLASS_DATE }}
            at ${{ env.CLASS_TIME }}
          body: >
            Job '${{ github.job }}' in worflow ${{ github.workflow }} of ${{ github.repository }} finished in a
            ${{ job.status }} state.

            See ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}.
          to: m@rtimlobao.com
          from: Regibox Auto-enroll
